on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install operating system dependencies
      run: npx playwright install-deps
    - name: Run your tests
      run: npm test
    - name: run tests
      run: npm test
