on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    # - name: Install operating system dependencies
    #   run: npx playwright install-deps
    - name: Install project dependencies
      run: npm install
    - name: Install PW
      run: npx playwright install 
    - name: prepare scratch org
      run: node sfdx-auth/spinScratchOrg.js ${{ secrets.DEVHUB_TOKEN }}
    - name: run tests
      run: npm test
      uses: actions/upload-artifact@v2
      with:
        name: playwright-test-report
        path: test-results/**
        retention-days: 1
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: playwright-test-report
        path: test-results/**
        retention-days: 1
