on:
  workflow_dispatch:

jobs:
  sandbox-org-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    # - name: install SFDX CLI and prepare credentials for sandbox org
    #   run: |
    #     wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
    #     mkdir ~/sfdx
    #     tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
    #     export PATH=~/sfdx/bin:$PATH
    #     sfdx plugins --core
    #     npx ts-node sfdx-auth/authSandbox.ts ${{ secrets.DEVHUB_TOKEN }} ${{ secrets.SANDBOX_PASS }}
    - name: Install SFDX CLI and prepare credentials for sandbox org
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
        mkdir ~/sfdx
        tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
        echo "~/sfdx/bin" >> $GITHUB_PATH
        sfdx plugins --core
    - name: Install project dependencies
      run: npm install
    - name: Install PW
      run: npx playwright install   
    - name: Prepare credentials for sandbox org
      run: npx ts-node sfdx-auth/authSandbox.ts ${{ secrets.DEVHUB_TOKEN }} ${{ secrets.SANDBOX_PASS }}
    - name: Run tests
      run: npm test
    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: playwright-test-report
        path: test-results/**
        retention-days: 1
